### ISSUE TITLE
Fix please 

### ISSUE THREAD

**Issue by iiInfinityHD** [fengberd/FNPC#14]
08.11 14:14:32 [Disconnect] User MagicPanda has disconnected, reason: unknown
08.11 14:14:20 [Server] | Elywing thread:INFO  MagicPanda[/72.193.200.62:19132] logged out due to client disconnect
08.11 14:14:20 [Server] | Elywing thread:INFO  MagicPanda left the game
08.11 14:14:15 [Server] | Elywing thread:CRITICAL  Error: "Undefined class constant 'DATA_SHOW_NAMETAG'" (EXCEPTION) in "/phar_FNPC-master_vdEF9mrgvx3xsXX.phar/src/FNPC/npc/NPC" at line 491
08.11 14:14:15 [Server] | Elywing thread:CRITICAL  Unhandled exception executing command 'fnpc add command 2 hi' in fnpc: Undefined class constant 'DATA_SHOW_NAMETAG'

**Comment by ondraczsk** [comment]
do you using 15.0 genisys or 16.0 genisys
