### ISSUE TITLE
Skins and more.

### ISSUE THREAD

**Issue by thebigsmileXD** [fengberd/FNPC#4]
Hey, just saw you went from a "private" repo to github. Cool thing.
I really like FNPC, the fact they are watching you is great.
I have some troubles with skins, i tried alot to fix them already..
I always see my own skin. Setting the skin data manually does nothing, resending the playerlistdatapacket neither. Any ideas?

**Comment by Praxthisnovcht** [comment]
it works fine, no need to fix anything lol

**Comment by SalmonGER** [comment]
@Praxthisnovcht could you explain us then how you did that? :)

**Comment by Praxthisnovcht** [comment]
/fnpc skin <ID> <file>

as indicated

**Comment by thebigsmileXD** [comment]
Still shows up as me

**Comment by Aericio** [comment]
Works for me too.

**Comment by thebigsmileXD** [comment]
Thanks for bumping, it was a core bug (not sending skin to client again)
Sadly still happens on world change though
